# Generated by Django 2.1.5 on 2024-10-15 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20241015_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image1',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image4',
        ),
    ]
