# Generated by Django 2.1.5 on 2024-10-15 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20241015_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='images',
            new_name='image',
        ),
    ]
