# Generated by Django 2.1.5 on 2024-11-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20241119_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, help_text='Link to the GitHub repository', null=True),
        ),
    ]
